//! Golden Test framework.
//!
//! Golden files are JSON files generated by ta-lib (Python binding) and stored
//! under `tests/golden/`. They serve as the **authoritative reference** for
//! numerical correctness.
//!
//! # File Format
//!
//! Single-output indicator (e.g. SMA):
//! ```json
//! {
//!   "meta": {
//!     "indicator": "sma",
//!     "params": { "period": 20 },
//!     "talib_version": "0.4.28",
//!     "generated_at": "2025-01-01T00:00:00Z",
//!     "dataset": "normal_1000"
//!   },
//!   "input": { "close": [102.5, 103.1, ...] },
//!   "output": { "values": [null, null, ..., 102.34, 103.12, ...] },
//!   "lookback": 19,
//!   "output_length": 981
//! }
//! ```
//!
//! Multi-output indicator (e.g. MACD):
//! ```json
//! {
//!   "output": { "macd": [...], "signal": [...], "hist": [...] }
//! }
//! ```
//!
//! `null` entries represent the lookback period (ta-lib outputs NaN there).
//! The Rust verifier skips nulls and only compares valid (non-null) values.
//!
//! # Usage
//!
//! ```rust,no_run
//! use polars_ta_verify::golden::{load_golden_file, assert_close};
//! use polars_ta_core::trend::sma;
//!
//! let golden = load_golden_file("tests/golden/sma_period20_normal_1000.json").unwrap();
//! let input = golden.close_input().unwrap();
//! let actual = sma(&input, 20);
//! assert_close(&actual, golden.get_output_values("values").unwrap(), 1e-10, "sma/normal_1000");
//! ```

use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;

/// Metadata section of a golden file.
#[derive(Debug, Deserialize)]
pub struct GoldenMeta {
    pub indicator: String,
    pub params: HashMap<String, serde_json::Value>,
    pub talib_version: String,
    pub generated_at: Option<String>,
    pub dataset: String,
}

/// Full golden file structure.
#[derive(Debug, Deserialize)]
pub struct GoldenFile {
    pub meta: GoldenMeta,
    pub input: HashMap<String, Vec<serde_json::Value>>,
    /// Named output arrays. Single-output indicators use key `"values"`;
    /// multi-output indicators use indicator-specific keys (e.g. `"macd"`, `"signal"`, `"hist"`).
    pub output: HashMap<String, Vec<Option<f64>>>,
    pub lookback: usize,
    pub output_length: usize,
}

impl GoldenFile {
    /// Extract the `close` input column as `Vec<f64>`, with JSON `null` → `NaN`.
    pub fn close_input(&self) -> Result<Vec<f64>, String> {
        self.get_input("close")
    }

    /// Extract an arbitrary input column as `Vec<f64>`, with JSON `null` → `NaN`.
    pub fn get_input(&self, col: &str) -> Result<Vec<f64>, String> {
        self.input
            .get(col)
            .ok_or_else(|| format!("column '{}' not found in golden file input", col))
            .map(|vals| {
                vals.iter()
                    .map(|v| match v {
                        serde_json::Value::Number(n) => n.as_f64().unwrap_or(f64::NAN),
                        _ => f64::NAN,
                    })
                    .collect()
            })
    }

    /// Get a named output array by key (e.g. `"values"`, `"macd"`, `"signal"`).
    pub fn get_output_values(&self, key: &str) -> Result<&[Option<f64>], String> {
        self.output
            .get(key)
            .map(|v| v.as_slice())
            .ok_or_else(|| format!("output key '{}' not found in golden file; available: {:?}", key, self.output.keys().collect::<Vec<_>>()))
    }
}

/// Load and deserialize a golden JSON file from disk.
pub fn load_golden_file<P: AsRef<Path>>(path: P) -> Result<GoldenFile, String> {
    let path = path.as_ref();
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("failed to read '{}': {}", path.display(), e))?;
    serde_json::from_str(&content)
        .map_err(|e| format!("failed to parse '{}': {}", path.display(), e))
}

/// Compare `actual` output against golden reference values.
///
/// Filters to non-NaN `actual` values and non-`None` golden values,
/// then asserts both counts are equal and all values are within `epsilon`.
///
/// This handles ta-lib's NaN-propagation behavior: once a NaN enters the
/// sliding sum, ta-lib emits NaN for all subsequent positions. The golden
/// file encodes these as `null`; our output encodes them as `f64::NAN`.
/// Both are skipped, and only the valid portion is compared.
///
/// # Panics
///
/// Panics with a detailed message on length mismatch or value divergence.
pub fn assert_close(actual: &[f64], golden: &[Option<f64>], epsilon: f64, label: &str) {
    // 只取 golden 中有效值
    let valid_golden: Vec<(usize, f64)> = golden
        .iter()
        .enumerate()
        .filter_map(|(i, v)| v.map(|f| (i, f)))
        .collect();

    // 只取 actual 中有效值（跳过 NaN 和 Inf，与 golden 中的 null 对应）
    let valid_actual: Vec<f64> = actual
        .iter()
        .copied()
        .filter(|v| v.is_finite())
        .collect();

    assert_eq!(
        valid_actual.len(),
        valid_golden.len(),
        "[{}] 有效输出数量不一致: actual_valid={}, golden_valid={} (actual_total={})",
        label,
        valid_actual.len(),
        valid_golden.len(),
        actual.len(),
    );

    let mut failures = vec![];
    for (actual_val, (golden_idx, expected)) in valid_actual.iter().zip(valid_golden.iter()) {
        let diff = (actual_val - expected).abs();
        if diff > epsilon {
            failures.push(format!(
                "  golden_index={}: actual={:.15}, expected={:.15}, diff={:.2e}",
                golden_idx, actual_val, expected, diff
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "[{}] Golden Test 失败，共 {} 处超出 epsilon={:.0e}:\n{}",
            label,
            failures.len(),
            epsilon,
            failures.join("\n")
        );
    }
}

/// Like [`assert_close`] but accepts values that pass either an absolute OR a relative tolerance.
///
/// A value passes if `|actual - expected| <= abs_epsilon OR |actual - expected| / |expected| <= rel_epsilon`.
/// This is appropriate for math-transform functions (EXP, COSH, SINH, TAN) where outputs can be
/// very large, making absolute epsilon comparisons meaningless, while relative error stays near
/// machine epsilon.
pub fn assert_close_relative(
    actual: &[f64],
    golden: &[Option<f64>],
    abs_epsilon: f64,
    rel_epsilon: f64,
    label: &str,
) {
    let valid_golden: Vec<(usize, f64)> = golden
        .iter()
        .enumerate()
        .filter_map(|(i, v)| v.map(|f| (i, f)))
        .collect();

    let valid_actual: Vec<f64> = actual
        .iter()
        .copied()
        .filter(|v| v.is_finite())
        .collect();

    assert_eq!(
        valid_actual.len(),
        valid_golden.len(),
        "[{}] 有效输出数量不一致: actual_valid={}, golden_valid={} (actual_total={})",
        label,
        valid_actual.len(),
        valid_golden.len(),
        actual.len(),
    );

    let mut failures = vec![];
    for (actual_val, (golden_idx, expected)) in valid_actual.iter().zip(valid_golden.iter()) {
        let diff = (actual_val - expected).abs();
        let rel_diff = if expected.abs() > 0.0 { diff / expected.abs() } else { diff };
        if diff > abs_epsilon && rel_diff > rel_epsilon {
            failures.push(format!(
                "  golden_index={}: actual={:.15e}, expected={:.15e}, abs_diff={:.2e}, rel_diff={:.2e}",
                golden_idx, actual_val, expected, diff, rel_diff
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "[{}] Golden Test 失败，共 {} 处超出 abs_epsilon={:.0e} 且 rel_epsilon={:.0e}:\n{}",
            label,
            failures.len(),
            abs_epsilon,
            rel_epsilon,
            failures.join("\n")
        );
    }
}

/// Summary result for a single golden test run (used by the report runner).
#[derive(Debug)]
pub struct GoldenTestResult {
    pub label: String,
    pub passed: bool,
    pub max_diff: f64,
    pub failure_count: usize,
    pub actual_len: usize,
    pub expected_len: usize,
}

/// Like [`assert_close`] but returns a [`GoldenTestResult`] instead of panicking.
pub fn check_close(actual: &[f64], golden: &[Option<f64>], epsilon: f64, label: &str) -> GoldenTestResult {
    let valid_golden: Vec<(usize, f64)> = golden
        .iter()
        .enumerate()
        .filter_map(|(i, v)| v.map(|f| (i, f)))
        .collect();

    let valid_actual: Vec<f64> = actual.iter().copied().filter(|v| !v.is_nan()).collect();

    if valid_actual.len() != valid_golden.len() {
        return GoldenTestResult {
            label: label.to_string(),
            passed: false,
            max_diff: f64::INFINITY,
            failure_count: 1,
            actual_len: valid_actual.len(),
            expected_len: valid_golden.len(),
        };
    }

    let mut max_diff = 0.0f64;
    let mut failure_count = 0usize;

    for (actual_val, (_golden_idx, expected)) in valid_actual.iter().zip(valid_golden.iter()) {
        let diff = (actual_val - expected).abs();
        if diff > max_diff {
            max_diff = diff;
        }
        if diff > epsilon {
            failure_count += 1;
        }
    }

    GoldenTestResult {
        label: label.to_string(),
        passed: failure_count == 0,
        max_diff,
        failure_count,
        actual_len: valid_actual.len(),
        expected_len: valid_golden.len(),
    }
}

/// Like [`check_close`] but accepts both absolute and relative tolerances.
///
/// A value passes if `|diff| <= abs_eps` OR `|diff| / |expected|.max(1e-300) <= rel_eps`.
/// Use `rel_eps = 0.0` to disable the relative check.
pub fn check_close_relative(
    actual: &[f64],
    golden: &[Option<f64>],
    abs_eps: f64,
    rel_eps: f64,
    label: &str,
) -> GoldenTestResult {
    let valid_golden: Vec<(usize, f64)> = golden
        .iter()
        .enumerate()
        .filter_map(|(i, v)| v.map(|f| (i, f)))
        .collect();

    let valid_actual: Vec<f64> = actual.iter().copied().filter(|v| !v.is_nan()).collect();

    if valid_actual.len() != valid_golden.len() {
        return GoldenTestResult {
            label: label.to_string(),
            passed: false,
            max_diff: f64::INFINITY,
            failure_count: 1,
            actual_len: valid_actual.len(),
            expected_len: valid_golden.len(),
        };
    }

    let mut max_diff = 0.0f64;
    let mut failure_count = 0usize;

    for (actual_val, (_golden_idx, expected)) in valid_actual.iter().zip(valid_golden.iter()) {
        let diff = (actual_val - expected).abs();
        if diff > max_diff {
            max_diff = diff;
        }
        let abs_ok = diff <= abs_eps;
        let rel_ok = rel_eps > 0.0 && diff / expected.abs().max(1e-300) <= rel_eps;
        if !abs_ok && !rel_ok {
            failure_count += 1;
        }
    }

    GoldenTestResult {
        label: label.to_string(),
        passed: failure_count == 0,
        max_diff,
        failure_count,
        actual_len: valid_actual.len(),
        expected_len: valid_golden.len(),
    }
}
