//! Golden Tests for SMA.
//!
//! Verifies numerical parity between `polars-ta-core::trend::sma` and ta-lib C.
//! Golden files are generated by `scripts/generate_golden.py` and stored in
//! `tests/golden/`.
//!
//! Run with: `cargo test --package polars-ta-verify`

use polars_ta_core::trend::sma;
use polars_ta_verify::golden::{assert_close, load_golden_file};
use std::path::PathBuf;

fn golden_path(filename: &str) -> PathBuf {
    // 从 workspace 根目录查找 golden 文件
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("tests")
        .join("golden")
        .join(filename)
}

/// 辅助：运行单个 SMA golden test
fn run_sma_golden(filename: &str, period: usize, epsilon: f64) {
    let path = golden_path(filename);
    if !path.exists() {
        println!("SKIP: golden file not found: {} (run scripts/generate_golden.py first)", filename);
        return;
    }
    let golden = load_golden_file(&path)
        .unwrap_or_else(|e| panic!("Failed to load {}: {}", filename, e));

    let input = golden.close_input()
        .unwrap_or_else(|e| panic!("Failed to parse input from {}: {}", filename, e));

    let actual = sma(&input, period);
    let label = format!("sma(period={})/{}", period, golden.meta.dataset);
    assert_close(&actual, golden.get_output_values("values").unwrap(), epsilon, &label);
}

#[test]
fn sma_period20_normal_1000() {
    run_sma_golden("sma_period20_normal_1000.json", 20, 1e-10);
}

#[test]
fn sma_period20_boundary_exact() {
    run_sma_golden("sma_period20_boundary_exact.json", 20, 1e-10);
}

#[test]
fn sma_period20_boundary_short() {
    // 输入长度 < period → 应返回空 Vec
    let data = vec![1.0f64; 19]; // period=20, lookback=19, need 20 for 1 output
    let result = sma(&data, 20);
    assert!(result.is_empty(), "输入不足时应返回空 Vec，got len={}", result.len());
}

#[test]
fn sma_period20_with_nan() {
    run_sma_golden("sma_period20_with_nan_5pct.json", 20, 1e-10);
}

#[test]
fn sma_period20_all_same_value() {
    run_sma_golden("sma_period20_all_same_value.json", 20, 1e-10);
}

#[test]
fn sma_period20_real_btcusdt() {
    // BTC 价格约 ~120,000，浮点累积误差约 2e-10，使用宽松 epsilon=1e-7
    // 原因：大数值下滑动累加的舍入误差与 ta-lib C 的单精度路径存在微小差异
    run_sma_golden("sma_period20_real_btcusdt_1d.json", 20, 1e-7);
}

#[test]
fn sma_period20_real_flat_period() {
    run_sma_golden("sma_period20_real_flat_period.json", 20, 1e-10);
}
